import turtle
grinch = turtle.Turtle()
print(grinch)
grinch.pensize(10)
grinch.color("green")
grinch.fillcolor("green")

grinch.speed(10)

# christmas tree body

grinch.begin_fill()
grinch.fd(30)
grinch.left(90)
grinch.fd(25)
grinch.right(90)
grinch.fd(150)
grinch.left(135)
grinch.fd(60)
grinch.right(135)
grinch.fd(25)
grinch.left(135)
grinch.fd(60)
grinch.right(135)
grinch.fd(25)
grinch.left(135)
grinch.fd(60)
grinch.right(135)
grinch.fd(25)
grinch.left(135)
grinch.fd(60)
grinch.right(135)
grinch.fd(25)
grinch.left(135)
grinch.fd(60)
grinch.right(135)
grinch.fd(25)
grinch.left(135)
grinch.fd(60)
grinch.right(135)
grinch.fd(25)
grinch.left(135)
grinch.fd(60)
grinch.right(135)
grinch.fd(25)
grinch.left(135)
grinch.fd(75)

grinch.left(90)
grinch.fd(75)
grinch.left(135)
grinch.fd(25)
grinch.right(135)
grinch.fd(60)
grinch.left(135)
grinch.fd(25)
grinch.right(135)
grinch.fd(60)
grinch.left(135)
grinch.fd(25)
grinch.right(135)
grinch.fd(60)
grinch.left(135)
grinch.fd(25)
grinch.right(135)
grinch.fd(60)
grinch.left(135)
grinch.fd(25)
grinch.right(135)
grinch.fd(60)
grinch.left(135)
grinch.fd(25)
grinch.right(135)
grinch.fd(60)
grinch.left(135)
grinch.fd(25)
grinch.right(135)
grinch.fd(60)
grinch.left(135)
grinch.fd(150)
grinch.right(90)
grinch.fd(25)
grinch.left(90)
grinch.fd(15)

grinch.end_fill()

# red ornament
grinch.penup()
grinch.goto(-75, 50)
grinch.pendown()
grinch.color("red")
grinch.fillcolor("red")
grinch.begin_fill()
grinch.circle(20)
grinch.end_fill()

# blue ornament
grinch.penup()
grinch.goto(-30, 250)
grinch.pendown()
grinch.color("blue")
grinch.fillcolor("blue")
grinch.begin_fill()
grinch.circle(20)
grinch.end_fill()

# violet ornament
grinch.penup()
grinch.goto(145, 20)
grinch.pendown()
grinch.color("violet")
grinch.fillcolor("violet")
grinch.begin_fill()
grinch.circle(12)
grinch.end_fill()

# orange ornament
grinch.penup()
grinch.goto(-80, 150)
grinch.pendown()
grinch.color("orange")
grinch.fillcolor("orange")
grinch.begin_fill()
grinch.circle(15)
grinch.end_fill()

# light coral ornament
grinch.penup()
grinch.goto(90, 175)
grinch.pendown()
grinch.color("light coral")
grinch.fillcolor("light coral")
grinch.begin_fill()
grinch.circle(17)
grinch.end_fill()

# white ornament
grinch.penup()
grinch.goto(50, 110)
grinch.pendown()
grinch.color("white")
grinch.fillcolor("white")
grinch.begin_fill()
grinch.circle(17)
grinch.end_fill()

# yellow star on top
def star(n = 5):
    t = turtle.Turtle()
    t.color("yellow")
    t.fillcolor("yellow")
    t.pensize(12)
    t.speed(10)
    t.penup()
    t.goto(-25, 385)
    t.pendown()
    t.begin_fill()
    for i in range(n):
        t.forward(55)
        t.right(144)

    t.end_fill()

star()
turtle.mainloop()